{'content': <Response [200]>,
 'links': {'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js': {'content': <Response [200]>,
                                                                               'links': {'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js': {'crawl_status': False,
                                                                                                                                                             'reason': 'RECURSIVE_LOOP'}},
                                                                               'response_status': 200,
                                                                               'stats': {'time': 474.41911697387695}},
           'http://blog.python.org': {'crawl_status': False,
                                      'reason': 'RECURSIVE_LOOP'},
           'http://bottlepy.org': {'crawl_status': False,
                                   'reason': 'RECURSIVE_LOOP'},
           'http://browsehappy.com/': {'content': <Response [200]>,
                                       'links': {'http://browsehappy.com/content/themes/browsehappy/imgs/apple-touch-icon-114x114.png': {'crawl_status': False,
                                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                         'stats': {'time': 0.005245208740234375}},
                                                 'http://browsehappy.com/content/themes/browsehappy/imgs/apple-touch-icon-57x57.png': {'crawl_status': False,
                                                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                       'stats': {'time': 0.0059604644775390625}},
                                                 'http://browsehappy.com/content/themes/browsehappy/imgs/apple-touch-icon-72x72.png': {'crawl_status': False,
                                                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                       'stats': {'time': 0.0059604644775390625}},
                                                 'http://browsehappy.com/content/themes/browsehappy/style.css?3': {'crawl_status': False,
                                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                                   'stats': {'time': 0.005245208740234375}},
                                                 'http://browsehappy.com/favicon.ico': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.00858306884765625}},
                                                 'http://browsehappy.com/wp/wp-includes/wlwmanifest.xml': {'crawl_status': False,
                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                           'stats': {'time': 0.005245208740234375}},
                                                 'http://browsehappy.com/wp/xmlrpc.php?rsd': {'crawl_status': False,
                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                              'stats': {'time': 0.005245208740234375}},
                                                 'http://twitter.com/share?url=http%3A%2F%2Fbrowsehappy.com%2F&amp;text=Browse+Happy%3A+Online.+Worry-free.+Upgrade+your+browser+today%21': {'crawl_status': False,
                                                                                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                             'stats': {'time': 0.0050067901611328125}},
                                                 'http://windows.microsoft.com/ie': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.005245208740234375}},
                                                 'http://wordpress.org/': {'crawl_status': False,
                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                           'stats': {'time': 0.0050067901611328125}},
                                                 'http://www.apple.com/safari/': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.0050067901611328125}},
                                                 'http://www.facebook.com/dialog/feed?app_id=180651631983617&link=http://browsehappy.com/&picture=http://browsehappy.com/content/themes/browsehappy/imgs/apple-touch-icon-114x114.png&name=Browse+Happy&description=Using+an+outdated+browser+makes+your+computer+unsafe.+Browse+Happy+is+a+way+for+you+to+find+out+what+are+the+latest+versions+of+the+major+browsers+around.+You+can+also+learn+about+alternative+browsers+that+may+fit+you+even+better+than+the+one+you+are+currently+using.&message=Online.+Worry-free.+Upgrade+your+browser+today%21&display=popup&redirect_uri=http://browsehappy.com/': {'crawl_status': False,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'stats': {'time': 0.0057220458984375}},
                                                 'http://www.firefox.com/': {'crawl_status': False,
                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                             'stats': {'time': 0.00476837158203125}},
                                                 'http://www.google.com/chrome': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.0050067901611328125}},
                                                 'http://www.opera.com/': {'crawl_status': False,
                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                           'stats': {'time': 0.0050067901611328125}}},
                                       'response_status': 200,
                                       'stats': {'time': 1544.5213317871094}},
           'http://bugs.python.org/': {'crawl_status': False,
                                       'reason': 'RECURSIVE_LOOP'},
           'http://buildbot.net/': {'crawl_status': False,
                                    'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/3/tutorial/': {'crawl_status': False,
                                                  'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/3/tutorial/controlflow.html': {'crawl_status': False,
                                                                  'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/3/tutorial/controlflow.html#defining-functions': {'crawl_status': False,
                                                                                     'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/3/tutorial/introduction.html#lists': {'crawl_status': False,
                                                                         'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator': {'crawl_status': False,
                                                                                                'reason': 'RECURSIVE_LOOP'},
           'http://docs.python.org/devguide/': {'crawl_status': False,
                                                'reason': 'RECURSIVE_LOOP'},
           'http://feedproxy.google.com/~r/PythonInsider/~3/AJ6AMDcjGaE/python-3.html': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
           'http://feedproxy.google.com/~r/PythonInsider/~3/FTlNOgFndNo/python-2710-release-candidate-1.html': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
           'http://feedproxy.google.com/~r/PythonInsider/~3/WgVFScO85Is/python-279-released.html': {'crawl_status': False,
                                                                                                    'reason': 'RECURSIVE_LOOP'},
           'http://feedproxy.google.com/~r/PythonInsider/~3/bpqbSnIQYCM/python-350a3-released.html': {'crawl_status': False,
                                                                                                      'reason': 'RECURSIVE_LOOP'},
           'http://feedproxy.google.com/~r/PythonInsider/~3/eb3JkcqpXBQ/ironpython-275-released.html': {'crawl_status': False,
                                                                                                        'reason': 'RECURSIVE_LOOP'},
           'http://flask.pocoo.org/': {'crawl_status': False,
                                       'reason': 'RECURSIVE_LOOP'},
           'http://ipython.org': {'crawl_status': False,
                                  'reason': 'RECURSIVE_LOOP'},
           'http://jobs.python.org': {'crawl_status': False,
                                      'reason': 'RECURSIVE_LOOP'},
           'http://pandas.pydata.org/': {'crawl_status': False,
                                         'reason': 'RECURSIVE_LOOP'},
           'http://planetpython.org/': {'crawl_status': False,
                                        'reason': 'RECURSIVE_LOOP'},
           'http://plus.google.com/+Python': {'crawl_status': False,
                                              'reason': 'RECURSIVE_LOOP'},
           'http://pycon.blogspot.com/': {'crawl_status': False,
                                          'reason': 'RECURSIVE_LOOP'},
           'http://pyfound.blogspot.com/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'http://python.org/dev/peps/': {'crawl_status': False,
                                           'reason': 'RECURSIVE_LOOP'},
           'http://pythonmentors.com/': {'crawl_status': False,
                                         'reason': 'RECURSIVE_LOOP'},
           'http://roundup.sourceforge.net/': {'crawl_status': False,
                                               'reason': 'RECURSIVE_LOOP'},
           'http://tornadoweb.org': {'crawl_status': False,
                                     'reason': 'RECURSIVE_LOOP'},
           'http://trac.edgewall.org/': {'crawl_status': False,
                                         'reason': 'RECURSIVE_LOOP'},
           'http://twitter.com/ThePSF': {'crawl_status': False,
                                         'reason': 'RECURSIVE_LOOP'},
           'http://wiki.python.org/moin/Languages': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'http://wiki.python.org/moin/TkInter': {'crawl_status': False,
                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.ansible.com': {'crawl_status': False,
                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.djangoproject.com/': {'crawl_status': False,
                                             'reason': 'RECURSIVE_LOOP'},
           'http://www.facebook.com/pythonlang?fref=ts': {'crawl_status': False,
                                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.google.com/chromeframe/?redirect=true': {'crawl_status': False,
                                                                'reason': 'RESPONSE_FAIL',
                                                                'response_error': 'Not '
                                                                                  'Found',
                                                                'response_status': 404,
                                                                'stats': {'time': 253.662109375}},
           'http://www.ie6countdown.com/': {'content': <Response [200]>,
                                            'links': {'http://modernumbraco.blob.core.windows.net/cdn/stylesheet/cdn/css/events/780d7355cd63cca1a9f4e598a927b59c214c6cd6.css': {'crawl_status': False,
                                                                                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                'stats': {'time': 0.004291534423828125}},
                                                      'http://modernumbraco.blob.core.windows.net/cdn/stylesheet/cdn/css/global/ef6cc9d9fbd9388e9758046d15aa52cf5cfd4a33.css': {'crawl_status': False,
                                                                                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                'stats': {'time': 0.0040531158447265625}},
                                                      'http://modernumbraco.blob.core.windows.net/cdn/stylesheet/cdn/css/pages/escape.less/745eda027944e98ffd6c08f059fbb56992b32211.css': {'crawl_status': False,
                                                                                                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                           'stats': {'time': 0.004291534423828125}},
                                                      'http://modernumbraco.blob.core.windows.net/cdn/stylesheet/cdn/ie6countdown/css/6d6e8737cdb6f60316eaaa41eb8a39ffcb35a981.css': {'crawl_status': False,
                                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                      'stats': {'time': 0.004291534423828125}},
                                                      'http://msdn.microsoft.com/windows/apps/cc300389': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.0050067901611328125}},
                                                      'http://stackoverflow.com/questions/tagged/internet-explorer': {'crawl_status': False,
                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                      'stats': {'time': 0.004291534423828125}},
                                                      'http://status.modern.ie': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.00476837158203125}},
                                                      'http://windows.microsoft.com/en-us/internet-explorer/download-ie': {'crawl_status': False,
                                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                                           'stats': {'time': 0.005245208740234375}},
                                                      'http://www.ie6countdown.com/': {'crawl_status': False,
                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/de-de': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/en-gb': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/en-us': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/en-us/': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.003814697265625}},
                                                      'http://www.ie6countdown.com/en-us/meet-developers': {'crawl_status': False,
                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                            'stats': {'time': 0.0045299530029296875}},
                                                      'http://www.ie6countdown.com/en-us/tools': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.0050067901611328125}},
                                                      'http://www.ie6countdown.com/en-us/virtualization-tools#downloads': {'crawl_status': False,
                                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                                           'stats': {'time': 0.0045299530029296875}},
                                                      'http://www.ie6countdown.com/es-es': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/favicon.ico': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.00476837158203125}},
                                                      'http://www.ie6countdown.com/feedback': {'crawl_status': False,
                                                                                               'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/fr-fr': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/it-it': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/ja-jp': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/ko-kr': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/pt-br': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/ru-ru': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/zh-cn': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.ie6countdown.com/zh-tw': {'crawl_status': False,
                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                      'http://www.microsoft.com': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.0045299530029296875}},
                                                      'http://www.microsoft.com/info/privacy.mspx': {'crawl_status': False,
                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                     'stats': {'time': 0.004291534423828125}},
                                                      'http://www.microsoft.com/library/toolbar/3.0/trademarks/en-us.mspx': {'crawl_status': False,
                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                             'stats': {'time': 0.0050067901611328125}},
                                                      'http://www.netmarketshare.com/': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.004291534423828125}},
                                                      'https://devchannel.modern.ie/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.004291534423828125}},
                                                      'https://escapefromxp.azurewebsites.net/': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.00476837158203125}},
                                                      'https://twitter.com/iedevchat': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0045299530029296875}},
                                                      'https://twitter.com/share': {'crawl_status': False,
                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                    'stats': {'time': 0.0045299530029296875}},
                                                      'https://www.modern.ie/ie6countdown': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.007152557373046875}}},
                                            'response_status': 200,
                                            'stats': {'time': 5100.308179855347}},
           'http://www.pygtk.org': {'crawl_status': False,
                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.pylonsproject.org/': {'crawl_status': False,
                                             'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/': {'crawl_status': False,
                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/#content': {'content': <Response [200]>,
                                              'links': {'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js': {'crawl_status': False,
                                                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                        'http://blog.python.org': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.003337860107421875}},
                                                        'http://bottlepy.org': {'crawl_status': False,
                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://browsehappy.com/': {'crawl_status': False,
                                                                                    'reason': 'RECURSIVE_LOOP'},
                                                        'http://bugs.python.org/': {'crawl_status': False,
                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                    'stats': {'time': 0.00286102294921875}},
                                                        'http://buildbot.net/': {'crawl_status': False,
                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                 'stats': {'time': 0.00286102294921875}},
                                                        'http://docs.python.org/3/tutorial/': {'crawl_status': False,
                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                               'stats': {'time': 0.0030994415283203125}},
                                                        'http://docs.python.org/3/tutorial/controlflow.html': {'crawl_status': False,
                                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                                               'stats': {'time': 0.0030994415283203125}},
                                                        'http://docs.python.org/3/tutorial/controlflow.html#defining-functions': {'crawl_status': False,
                                                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                  'stats': {'time': 0.0030994415283203125}},
                                                        'http://docs.python.org/3/tutorial/introduction.html#lists': {'crawl_status': False,
                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                      'stats': {'time': 0.0030994415283203125}},
                                                        'http://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator': {'crawl_status': False,
                                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                             'stats': {'time': 0.0030994415283203125}},
                                                        'http://docs.python.org/devguide/': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.00286102294921875}},
                                                        'http://feedproxy.google.com/~r/PythonInsider/~3/AJ6AMDcjGaE/python-3.html': {'crawl_status': False,
                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                      'stats': {'time': 0.0030994415283203125}},
                                                        'http://feedproxy.google.com/~r/PythonInsider/~3/FTlNOgFndNo/python-2710-release-candidate-1.html': {'crawl_status': False,
                                                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                             'stats': {'time': 0.00286102294921875}},
                                                        'http://feedproxy.google.com/~r/PythonInsider/~3/WgVFScO85Is/python-279-released.html': {'crawl_status': False,
                                                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                 'stats': {'time': 0.00286102294921875}},
                                                        'http://feedproxy.google.com/~r/PythonInsider/~3/bpqbSnIQYCM/python-350a3-released.html': {'crawl_status': False,
                                                                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                   'stats': {'time': 0.0030994415283203125}},
                                                        'http://feedproxy.google.com/~r/PythonInsider/~3/eb3JkcqpXBQ/ironpython-275-released.html': {'crawl_status': False,
                                                                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                     'stats': {'time': 0.00286102294921875}},
                                                        'http://flask.pocoo.org/': {'crawl_status': False,
                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                    'stats': {'time': 0.0030994415283203125}},
                                                        'http://ipython.org': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.00286102294921875}},
                                                        'http://jobs.python.org': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.00286102294921875}},
                                                        'http://pandas.pydata.org/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0030994415283203125}},
                                                        'http://planetpython.org/': {'crawl_status': False,
                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                        'http://plus.google.com/+Python': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.00286102294921875}},
                                                        'http://pycon.blogspot.com/': {'crawl_status': False,
                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                        'http://pyfound.blogspot.com/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://python.org/dev/peps/': {'crawl_status': False,
                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                        'http://pythonmentors.com/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0026226043701171875}},
                                                        'http://roundup.sourceforge.net/': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.00286102294921875}},
                                                        'http://tornadoweb.org': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.00286102294921875}},
                                                        'http://trac.edgewall.org/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.00286102294921875}},
                                                        'http://twitter.com/ThePSF': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.00286102294921875}},
                                                        'http://wiki.python.org/moin/Languages': {'crawl_status': False,
                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://wiki.python.org/moin/TkInter': {'crawl_status': False,
                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://www.ansible.com': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.00286102294921875}},
                                                        'http://www.djangoproject.com/': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.00286102294921875}},
                                                        'http://www.facebook.com/pythonlang?fref=ts': {'crawl_status': False,
                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                       'stats': {'time': 0.003337860107421875}},
                                                        'http://www.google.com/chromeframe/?redirect=true': {'crawl_status': False,
                                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.ie6countdown.com/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.pygtk.org': {'crawl_status': False,
                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                 'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.pylonsproject.org/': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/': {'crawl_status': False,
                                                                                   'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/#content': {'crawl_status': False,
                                                                                           'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/#python-network': {'crawl_status': False,
                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/#site-map': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/#top': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/about/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/apps': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/about/apps/': {'crawl_status': False,
                                                                                              'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/gettingstarted/': {'crawl_status': False,
                                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/help/': {'crawl_status': False,
                                                                                              'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/legal/': {'crawl_status': False,
                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                               'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/about/quotes/': {'crawl_status': False,
                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/': {'crawl_status': False,
                                                                                                 'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#arts': {'crawl_status': False,
                                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#business': {'crawl_status': False,
                                                                                                          'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#education': {'crawl_status': False,
                                                                                                           'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#engineering': {'crawl_status': False,
                                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#government': {'crawl_status': False,
                                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#scientific': {'crawl_status': False,
                                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/about/success/#software-development': {'crawl_status': False,
                                                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/accounts/login/': {'crawl_status': False,
                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/accounts/signup/': {'crawl_status': False,
                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                   'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/blogs/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/': {'crawl_status': False,
                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/awards': {'crawl_status': False,
                                                                                                   'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/diversity/': {'crawl_status': False,
                                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/irc/': {'crawl_status': False,
                                                                                                 'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/lists/': {'crawl_status': False,
                                                                                                   'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/logos/': {'crawl_status': False,
                                                                                                   'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/merchandise/': {'crawl_status': False,
                                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/sigs/': {'crawl_status': False,
                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/community/workshops/': {'crawl_status': False,
                                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/dev/': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.0035762786865234375}},
                                                        'http://www.python.org/dev/peps/': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/dev/peps/peps.rss': {'crawl_status': False,
                                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                                    'stats': {'time': 0.003337860107421875}},
                                                        'http://www.python.org/doc/': {'crawl_status': False,
                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/doc/av': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/download/alternatives': {'crawl_status': False,
                                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/download/other/': {'crawl_status': False,
                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/downloads/': {'crawl_status': False,
                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/downloads/mac-osx/': {'crawl_status': False,
                                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/downloads/release/python-279/': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/downloads/release/python-343/': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/downloads/source/': {'crawl_status': False,
                                                                                                    'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/downloads/windows/': {'crawl_status': False,
                                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/events/': {'crawl_status': False,
                                                                                          'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/events/calendars/': {'crawl_status': False,
                                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                                    'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/events/python-events/': {'crawl_status': False,
                                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/events/python-events/278/': {'crawl_status': False,
                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                            'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/events/python-events/294/': {'crawl_status': False,
                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                            'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/events/python-events/311/': {'crawl_status': False,
                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                            'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/events/python-events/past/': {'crawl_status': False,
                                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/events/python-user-group/': {'crawl_status': False,
                                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/events/python-user-group/318/': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/events/python-user-group/323/': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/events/python-user-group/past/': {'crawl_status': False,
                                                                                                                 'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/jobs/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/privacy/': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.003337860107421875}},
                                                        'http://www.python.org/psf-landing/': {'crawl_status': False,
                                                                                               'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/psf/': {'crawl_status': False,
                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/psf/donations/': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/shell/': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0030994415283203125}},
                                                        'http://www.python.org/static/apple-touch-icon-114x114-precomposed.png': {'crawl_status': False,
                                                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/apple-touch-icon-144x144-precomposed.png': {'crawl_status': False,
                                                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/apple-touch-icon-72x72-precomposed.png': {'crawl_status': False,
                                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/apple-touch-icon-precomposed.png': {'crawl_status': False,
                                                                                                                          'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/favicon.ico': {'crawl_status': False,
                                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/humans.txt': {'crawl_status': False,
                                                                                                    'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/stylesheets/mq.css': {'crawl_status': False,
                                                                                                            'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/stylesheets/no-mq.css': {'crawl_status': False,
                                                                                                               'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/static/stylesheets/style.css': {'crawl_status': False,
                                                                                                               'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/success-stories/': {'crawl_status': False,
                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                   'stats': {'time': 0.00286102294921875}},
                                                        'http://www.python.org/success-stories/industrial-light-magic-runs-python/': {'crawl_status': False,
                                                                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                        'http://www.python.org/users/membership/': {'crawl_status': False,
                                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                                    'stats': {'time': 0.00286102294921875}},
                                                        'http://www.riverbankcomputing.co.uk/software/pyqt/intro': {'crawl_status': False,
                                                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                                                    'stats': {'time': 0.00286102294921875}},
                                                        'http://www.saltstack.com': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.00286102294921875}},
                                                        'http://www.scipy.org': {'crawl_status': False,
                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                 'stats': {'time': 0.003814697265625}},
                                                        'http://www.web2py.com/': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.00286102294921875}},
                                                        'http://www.wxpython.org/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0030994415283203125}},
                                                        'https://docs.python.org': {'crawl_status': False,
                                                                                    'reason': 'RECURSIVE_LOOP'},
                                                        'https://docs.python.org/3/license.html': {'crawl_status': False,
                                                                                                   'reason': 'RECURSIVE_LOOP'},
                                                        'https://docs.python.org/devguide/': {'crawl_status': False,
                                                                                              'reason': 'RECURSIVE_LOOP'},
                                                        'https://docs.python.org/faq/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                        'https://github.com/python/pythondotorg/issues': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.0030994415283203125}},
                                                        'https://mail.python.org/mailman/listinfo/python-dev': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.00286102294921875}},
                                                        'https://pypi.python.org/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0030994415283203125}},
                                                        'https://wiki.python.org/moin/': {'crawl_status': False,
                                                                                          'reason': 'RECURSIVE_LOOP'},
                                                        'https://wiki.python.org/moin/BeginnersGuide': {'crawl_status': False,
                                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                        'https://wiki.python.org/moin/Python2orPython3': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.00286102294921875}},
                                                        'https://wiki.python.org/moin/PythonBooks': {'crawl_status': False,
                                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                        'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event': {'crawl_status': False,
                                                                                                                                  'reason': 'RECURSIVE_LOOP'},
                                                        'https://www.openstack.org': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.00286102294921875}},
                                                        'javascript:;': {'crawl_status': False,
                                                                         'reason': 'RECURSIVE_LOOP'}},
                                              'response_status': 200,
                                              'stats': {'time': 821.8913078308105}},
           'http://www.python.org/#python-network': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/#site-map': {'crawl_status': False,
                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/#top': {'crawl_status': False,
                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/apps': {'crawl_status': False,
                                                'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/apps/': {'crawl_status': False,
                                                 'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/gettingstarted/': {'crawl_status': False,
                                                           'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/help/': {'crawl_status': False,
                                                 'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/legal/': {'crawl_status': False,
                                                  'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/quotes/': {'crawl_status': False,
                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/': {'crawl_status': False,
                                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#arts': {'crawl_status': False,
                                                         'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#business': {'crawl_status': False,
                                                             'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#education': {'crawl_status': False,
                                                              'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#engineering': {'crawl_status': False,
                                                                'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#government': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#scientific': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/about/success/#software-development': {'crawl_status': False,
                                                                         'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/accounts/login/': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/accounts/signup/': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/blogs/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/': {'crawl_status': False,
                                                'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/awards': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/diversity/': {'crawl_status': False,
                                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/irc/': {'crawl_status': False,
                                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/lists/': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/logos/': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/merchandise/': {'crawl_status': False,
                                                            'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/sigs/': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/community/workshops/': {'crawl_status': False,
                                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/dev/': {'crawl_status': False,
                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/dev/peps/': {'crawl_status': False,
                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/dev/peps/peps.rss': {'crawl_status': False,
                                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/doc/': {'crawl_status': False,
                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/doc/av': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/download/alternatives': {'crawl_status': False,
                                                           'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/download/other/': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/': {'crawl_status': False,
                                                'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/mac-osx/': {'crawl_status': False,
                                                        'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/release/python-279/': {'crawl_status': False,
                                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/release/python-343/': {'crawl_status': False,
                                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/source/': {'crawl_status': False,
                                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/downloads/windows/': {'crawl_status': False,
                                                        'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/': {'crawl_status': False,
                                             'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/calendars/': {'crawl_status': False,
                                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-events/': {'crawl_status': False,
                                                           'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-events/278/': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-events/294/': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-events/311/': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-events/past/': {'crawl_status': False,
                                                                'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-user-group/': {'crawl_status': False,
                                                               'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-user-group/318/': {'crawl_status': False,
                                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-user-group/323/': {'crawl_status': False,
                                                                   'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/events/python-user-group/past/': {'crawl_status': False,
                                                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/jobs/': {'crawl_status': False,
                                           'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/privacy/': {'crawl_status': False,
                                              'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/psf-landing/': {'crawl_status': False,
                                                  'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/psf/': {'crawl_status': False,
                                          'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/psf/donations/': {'crawl_status': False,
                                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/shell/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/static/apple-touch-icon-114x114-precomposed.png': {'content': <Response [200]>,
                                                                                     'links': {},
                                                                                     'response_status': 200,
                                                                                     'stats': {'time': 633.430004119873}},
           'http://www.python.org/static/apple-touch-icon-144x144-precomposed.png': {'content': <Response [200]>,
                                                                                     'links': {},
                                                                                     'response_status': 200,
                                                                                     'stats': {'time': 624.4227886199951}},
           'http://www.python.org/static/apple-touch-icon-72x72-precomposed.png': {'content': <Response [200]>,
                                                                                   'links': {},
                                                                                   'response_status': 200,
                                                                                   'stats': {'time': 679.8560619354248}},
           'http://www.python.org/static/apple-touch-icon-precomposed.png': {'crawl_status': False,
                                                                             'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/static/favicon.ico': {'content': <Response [200]>,
                                                        'links': {},
                                                        'response_status': 200,
                                                        'stats': {'time': 1021.1410522460938}},
           'http://www.python.org/static/humans.txt': {'content': <Response [200]>,
                                                       'links': {},
                                                       'response_status': 200,
                                                       'stats': {'time': 812.9973411560059}},
           'http://www.python.org/static/stylesheets/mq.css': {'content': <Response [200]>,
                                                               'links': {},
                                                               'response_status': 200,
                                                               'stats': {'time': 626.701831817627}},
           'http://www.python.org/static/stylesheets/no-mq.css': {'content': <Response [200]>,
                                                                  'links': {},
                                                                  'response_status': 200,
                                                                  'stats': {'time': 549.2913722991943}},
           'http://www.python.org/static/stylesheets/style.css': {'content': <Response [200]>,
                                                                  'links': {},
                                                                  'response_status': 200,
                                                                  'stats': {'time': 970.1147079467773}},
           'http://www.python.org/success-stories/': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/success-stories/industrial-light-magic-runs-python/': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
           'http://www.python.org/users/membership/': {'crawl_status': False,
                                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.riverbankcomputing.co.uk/software/pyqt/intro': {'crawl_status': False,
                                                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.saltstack.com': {'crawl_status': False,
                                        'reason': 'RECURSIVE_LOOP'},
           'http://www.scipy.org': {'crawl_status': False,
                                    'reason': 'RECURSIVE_LOOP'},
           'http://www.web2py.com/': {'crawl_status': False,
                                      'reason': 'RECURSIVE_LOOP'},
           'http://www.wxpython.org/': {'crawl_status': False,
                                        'reason': 'RECURSIVE_LOOP'},
           'https://docs.python.org': {'crawl_status': False,
                                       'reason': 'RECURSIVE_LOOP'},
           'https://docs.python.org/3/license.html': {'crawl_status': False,
                                                      'reason': 'RECURSIVE_LOOP'},
           'https://docs.python.org/devguide/': {'crawl_status': False,
                                                 'reason': 'RECURSIVE_LOOP'},
           'https://docs.python.org/faq/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP'},
           'https://github.com/python/pythondotorg/issues': {'crawl_status': False,
                                                             'reason': 'RECURSIVE_LOOP'},
           'https://mail.python.org/mailman/listinfo/python-dev': {'crawl_status': False,
                                                                   'reason': 'RECURSIVE_LOOP'},
           'https://pypi.python.org/': {'crawl_status': False,
                                        'reason': 'RECURSIVE_LOOP'},
           'https://wiki.python.org/moin/': {'crawl_status': False,
                                             'reason': 'RECURSIVE_LOOP'},
           'https://wiki.python.org/moin/BeginnersGuide': {'crawl_status': False,
                                                           'reason': 'RECURSIVE_LOOP'},
           'https://wiki.python.org/moin/Python2orPython3': {'crawl_status': False,
                                                             'reason': 'RECURSIVE_LOOP'},
           'https://wiki.python.org/moin/PythonBooks': {'crawl_status': False,
                                                        'reason': 'RECURSIVE_LOOP'},
           'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event': {'crawl_status': False,
                                                                                     'reason': 'RECURSIVE_LOOP'},
           'https://www.openstack.org': {'crawl_status': False,
                                         'reason': 'RECURSIVE_LOOP'},
           'javascript:;': {'crawl_status': False,
                            'reason': 'RECURSIVE_LOOP'}},
 'response_status': 200,
 'stats': {'time': 15574.474573135376}}
