{'content': <Response [200]>,
 'links': {'http://assets-0.housingcdn.com': {'crawl_status': False,
                                              'reason': 'RESPONSE_FAIL',
                                              'response_error': 'Forbidden',
                                              'response_status': 403,
                                              'stats': {'time': 208.14228057861328}},
           'http://assets-1.housingcdn.com': {'crawl_status': False,
                                              'reason': 'RESPONSE_FAIL',
                                              'response_error': 'Forbidden',
                                              'response_status': 403,
                                              'stats': {'time': 164.61563110351562}},
           'http://www.housing.com/': {'crawl_status': False,
                                       'reason': 'RECURSIVE_LOOP'},
           'http://www.housing.com/apps': {'content': <Response [200]>,
                                           'links': {'http://assets-0.housingcdn.com': {'crawl_status': False,
                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                     'http://assets-1.housingcdn.com': {'crawl_status': False,
                                                                                        'reason': 'RECURSIVE_LOOP'},
                                                     'http://www.housing.com/apps': {'crawl_status': False,
                                                                                     'reason': 'RECURSIVE_LOOP'},
                                                     'http://www.housing.com/careers': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0016689300537109375}},
                                                     'http://www.housing.com/osdd.xml': {'crawl_status': False,
                                                                                         'reason': 'RECURSIVE_LOOP'},
                                                     'http://www.housing.com/rent-sell-property': {'crawl_status': False,
                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                   'stats': {'time': 0.0016689300537109375}},
                                                     'http://www.indianrealestateforum.com/': {'crawl_status': False,
                                                                                               'reason': 'RECURSIVE_LOOP'},
                                                     'https://assets-0.housingcdn.com/website/website/all/desktop_common_woff-616ef824e632baf148b9997815cff302.css': {'crawl_status': False,
                                                                                                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                     'https://assets-1.housingcdn.com/website/website/single_page/mobile_apps-7c3be9180ed3e62638435bb98dcf5ad9.css': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0026226043701171875}},
                                                     'https://plus.google.com/+Housing-com': {'crawl_status': False,
                                                                                              'reason': 'RECURSIVE_LOOP'}},
                                           'response_status': 200,
                                           'stats': {'time': 778.489351272583}},
           'http://www.housing.com/careers': {'crawl_status': False,
                                              'reason': 'RECURSIVE_LOOP'},
           'http://www.housing.com/osdd.xml': {'content': <Response [200]>,
                                               'links': {},
                                               'response_status': 200,
                                               'stats': {'time': 579.857349395752}},
           'http://www.housing.com/rent-sell-property': {'crawl_status': False,
                                                         'reason': 'RECURSIVE_LOOP'},
           'http://www.indianrealestateforum.com/': {'crawl_status': False,
                                                     'reason': 'RECURSIVE_LOOP'},
           'https://assets-0.housingcdn.com/website/website/all/desktop_common_woff-616ef824e632baf148b9997815cff302.css': {'crawl_status': False,
                                                                                                                            'reason': 'RECURSIVE_LOOP'},
           'https://assets-1.housingcdn.com/website/website/all/desktop_home_page-951ca9cb3c6c3520b25b271b72362507.css': {'crawl_status': False,
                                                                                                                          'reason': 'RECURSIVE_LOOP'},
           'https://housing.com/': {'content': <Response [200]>,
                                    'links': {'http://www.indianrealestateforum.com/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0045299530029296875}},
                                              'https://assets-0.housingcdn.com': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.009298324584960938}},
                                              'https://assets-0.housingcdn.com/website/website/all/desktop_common_woff-616ef824e632baf148b9997815cff302.css': {'crawl_status': False,
                                                                                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                               'stats': {'time': 0.005245208740234375}},
                                              'https://assets-1.housingcdn.com': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.0057220458984375}},
                                              'https://assets-1.housingcdn.com/website/website/all/desktop_home_page-951ca9cb3c6c3520b25b271b72362507.css': {'crawl_status': False,
                                                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                             'stats': {'time': 0.005245208740234375}},
                                              'https://housing.com/': {'crawl_status': False,
                                                                       'reason': 'RECURSIVE_LOOP'},
                                              'https://housing.com/apps': {'crawl_status': False,
                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                           'stats': {'time': 0.0045299530029296875}},
                                              'https://housing.com/careers': {'crawl_status': False,
                                                                              'reason': 'RECURSIVE_LOOP'},
                                              'https://housing.com/osdd.xml': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.005245208740234375}},
                                              'https://housing.com/rent-sell-property': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0050067901611328125}},
                                              'https://plus.google.com/+Housing-com': {'crawl_status': False,
                                                                                       'reason': 'RECURSIVE_LOOP'}},
                                    'response_status': 200,
                                    'stats': {'time': 634.6135139465332}},
           'https://plus.google.com/+Housing-com': {'content': <Response [200]>,
                                                    'links': {'android-app://com.google.android.apps.plus/https/plus.google.com/+Housing-com': {'crawl_status': False,
                                                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                'stats': {'time': 0.004291534423828125}},
                                                              'http://bit.ly/1Bc33pf': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0011920928955078125}},
                                                              'http://en.wikipedia.org/wiki/Housing.com': {'crawl_status': False,
                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                           'stats': {'time': 0.001430511474609375}},
                                                              'http://housing.com/blog/': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.001430511474609375}},
                                                              'http://instagram.com/housingdotcom': {'crawl_status': False,
                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                     'stats': {'time': 0.0011920928955078125}},
                                                              'http://on.fb.me/1EEPEL2': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.001430511474609375}},
                                                              'http://on.fb.me/1EcjotO': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0011920928955078125}},
                                                              'http://www.google.co.in/history/optout?hl=en-GB': {'crawl_status': False,
                                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                                  'stats': {'time': 0.00476837158203125}},
                                                              'http://www.google.co.in/imghp?hl=en-GB&tab=Xi': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.004291534423828125}},
                                                              'http://www.google.co.in/intl/en-GB/options/': {'crawl_status': False,
                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                              'stats': {'time': 0.004291534423828125}},
                                                              'http://www.google.com/intl/en_uk/+/learnmore/forum/': {'crawl_status': False,
                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                      'stats': {'time': 0.0045299530029296875}},
                                                              'http://www.youtube.com/user/HousingY': {'crawl_status': False,
                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                       'stats': {'time': 0.0011920928955078125}},
                                                              'https://accounts.google.com/ServiceLogin?service=oz&passive=1209600&continue=https://plus.google.com/%2BHousing-com?gpsrc%3Dgplp0': {'crawl_status': False,
                                                                                                                                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                                    'stats': {'time': 0.0050067901611328125}},
                                                              'https://drive.google.com/?tab=Xo': {'crawl_status': False,
                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                   'stats': {'time': 0.00476837158203125}},
                                                              'https://housing.com': {'crawl_status': False,
                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                              'https://housing.com/blog/2015/04/30/a-tale-of-2-cities-now-in-numbers/': {'crawl_status': False,
                                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://housing.com/blog/2015/05/15/housings-tech-office-is-coming-to-your-city/': {'crawl_status': False,
                                                                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                   'stats': {'time': 0.0016689300537109375}},
                                                              'https://housing.com/careers': {'crawl_status': False,
                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                              'stats': {'time': 0.001430511474609375}},
                                                              'https://housing.com/in/pg': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0011920928955078125}},
                                                              'https://lnkd.in/by5-UXh': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.001430511474609375}},
                                                              'https://mail.google.com/mail/?tab=Xm': {'crawl_status': False,
                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                       'stats': {'time': 0.00476837158203125}},
                                                              'https://maps.google.co.in/maps?hl=en-GB&tab=Xl': {'crawl_status': False,
                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                 'stats': {'time': 0.00476837158203125}},
                                                              'https://play.google.com/?hl=en-GB&tab=X8': {'crawl_status': False,
                                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                                           'stats': {'time': 0.00476837158203125}},
                                                              'https://plus.google.com/': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.007867813110351562}},
                                                              'https://plus.google.com/+Housing-com': {'crawl_status': False,
                                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/+Housing-com/posts/6eUVxe64E76': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/6tVsS7S6bRq': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/8pqNypibcXM': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/+Housing-com/posts/8qh1PwW3dxA': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/AHH8YeGeYWN': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/AVse3qQUoef': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/+Housing-com/posts/JS9mWtiUgJC': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/+Housing-com/posts/LaV6T1MJ9YX': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/+Housing-com/posts/fBKtpeJvQG9': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.0011920928955078125}},
                                                              'https://plus.google.com/+Housing-com/posts/fbBG5i1NyPx': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/i5Nwzce2WQX': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/+Housing-com/posts/jp17mRm8Z9p': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/100617805328064298519': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/101667524224795128772': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/101962814887845453118': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/105484620557065118741': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/107415202466797629280': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/108186668097792754326': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/110175957625565018002': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/111641323940280795780': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/112851505978208320222': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/113397476177761656464': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/115490695052388961705': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/116205201651891465608': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/116390109264258994237': {'crawl_status': False,
                                                                                                                'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/_/scs/apps-static/_/ss/k=oz.home.-7biq1kwjx0bg.L.W.O/am=AHTYBCAQDABKAgAAAkAABABQ/d=0/rs=AGLTcCOZWXs1JENp7qMKWY0-4vTkU_nm5A': {'crawl_status': False,
                                                                                                                                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                                                     'stats': {'time': 0.005245208740234375}},
                                                              'https://plus.google.com/app/basic/+Housing-com': {'crawl_status': False,
                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                 'stats': {'time': 0.0040531158447265625}},
                                                              'https://plus.google.com/collections': {'crawl_status': False,
                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                      'stats': {'time': 0.012874603271484375}},
                                                              'https://plus.google.com/communities': {'crawl_status': False,
                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/dashboard?ppsrc=gpnv0': {'crawl_status': False,
                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/events': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/explore': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/hangouts': {'crawl_status': False,
                                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                                   'stats': {'time': 0.0011920928955078125}},
                                                              'https://plus.google.com/me': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.0045299530029296875}},
                                                              'https://plus.google.com/people': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.00476837158203125}},
                                                              'https://plus.google.com/photos': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.0059604644775390625}},
                                                              'https://plus.google.com/photos/116390109264258994237': {'crawl_status': False,
                                                                                                                       'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6143435590360803905/6143435594590363250': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6144909479698862993/6144909480120786866': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6145283906195101409/6145283910504836322': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6146488381206902817/6146488382031331042': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6147631165588836801/6147631170421138850': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6148006876925963265/6148006881171355794': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6149111509764971473/6149111507242479842': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6149452818328664897/6149452820202399762': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6149715613349754209/6149715615596985474': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6149748770135478753/6149748776277467170': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6150821845929996801/6150821850428645602': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.0016689300537109375}},
                                                              'https://plus.google.com/photos/116390109264258994237/albums/6151225517510888673/6151225515593760866': {'crawl_status': False,
                                                                                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                      'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/s/%23GuessTheCity': {'crawl_status': False,
                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                            'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/s/%23LookUpLife': {'crawl_status': False,
                                                                                                          'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/s/%23LookUpMoments': {'crawl_status': False,
                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                             'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/s/%23LookUpWindows': {'crawl_status': False,
                                                                                                             'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/s/%23contest': {'crawl_status': False,
                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                       'stats': {'time': 0.001430511474609375}},
                                                              'https://plus.google.com/s/%23lookup': {'crawl_status': False,
                                                                                                      'reason': 'RECURSIVE_LOOP'},
                                                              'https://plus.google.com/settings/plus': {'crawl_status': False,
                                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                                        'stats': {'time': 0.0011920928955078125}},
                                                              'https://plus.google.com/stream': {'crawl_status': False,
                                                                                                 'reason': 'RECURSIVE_LOOP'},
                                                              'https://ssl.gstatic.com/s2/oz/images/faviconr3.ico': {'crawl_status': False,
                                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                                     'stats': {'time': 0.0045299530029296875}},
                                                              'https://twitter.com/Housing': {'crawl_status': False,
                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                              'stats': {'time': 0.0016689300537109375}},
                                                              'https://www.facebook.com/housing.com': {'crawl_status': False,
                                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                                       'stats': {'time': 0.0011920928955078125}},
                                                              'https://www.google.co.in/webhp?tab=Xw': {'crawl_status': False,
                                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                                        'stats': {'time': 0.005245208740234375}},
                                                              'https://www.google.com/calendar?tab=Xc': {'crawl_status': False,
                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                         'stats': {'time': 0.0045299530029296875}},
                                                              'https://www.google.com/intl/en_uk/+/policy/': {'crawl_status': False,
                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                              'stats': {'time': 0.001430511474609375}},
                                                              'https://www.google.com/intl/en_uk/+/policy/content.html': {'crawl_status': False,
                                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                                          'stats': {'time': 0.001430511474609375}},
                                                              'https://www.google.com/intl/en_uk/help/terms_maps.html': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.001430511474609375}},
                                                              'https://www.google.com/support/profiles/?p=help_center&hl=en-GB': {'crawl_status': False,
                                                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                  'stats': {'time': 0.0054836273193359375}},
                                                              'https://www.youtube.com/?tab=X1': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.0050067901611328125}},
                                                              'ios-app://447119634/gplus/plus.google.com/+Housing-com': {'crawl_status': False,
                                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                                         'stats': {'time': 0.004291534423828125}},
                                                              'javascript:void(0);': {'crawl_status': False,
                                                                                      'reason': 'RECURSIVE_LOOP'}},
                                                    'response_status': 200,
                                                    'stats': {'time': 1581.1333656311035}}},
 'response_status': 200,
 'stats': {'time': 4685.5788230896}}
