{'content': <Response [200]>,
 'links': {'http://localhost/../': {'crawl_status': False,
                                    'reason': 'RESPONSE_FAIL',
                                    'response_error': 'Bad Request',
                                    'response_status': 400,
                                    'stats': {'time': 2.2051334381103516}},
           'http://localhost/ansible/': {'content': <Response [200]>,
                                         'links': {'http://localhost/': {'crawl_status': False,
                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                         'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ansible/README.md': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.001430511474609375}},
                                                   'http://localhost/ansible/ansible.cfg': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0011920928955078125}},
                                                   'http://localhost/ansible/ansible.log': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.001430511474609375}},
                                                   'http://localhost/ansible/group_vars/': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0016689300537109375}},
                                                   'http://localhost/ansible/hosts/': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.001430511474609375}},
                                                   'http://localhost/ansible/roles/': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.001430511474609375}},
                                                   'http://localhost/ansible/site.yml': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.001430511474609375}}},
                                         'response_status': 200,
                                         'stats': {'time': 2.996206283569336}},
           'http://localhost/costa.pdf': {'content': <Response [200]>,
                                          'links': {},
                                          'response_status': 200,
                                          'stats': {'time': 1045.4065799713135}},
           'http://localhost/dwm/': {'content': <Response [200]>,
                                     'links': {'http://localhost/': {'crawl_status': False,
                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                     'stats': {'time': 0.0021457672119140625}},
                                               'http://localhost/dwm/BUGS': {'crawl_status': False,
                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                             'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/LICENSE': {'crawl_status': False,
                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/Makefile': {'crawl_status': False,
                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                 'stats': {'time': 0.0011920928955078125}},
                                               'http://localhost/dwm/README': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.0011920928955078125}},
                                               'http://localhost/dwm/TODO': {'crawl_status': False,
                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                             'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/config.def.h': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/config.mk': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.0016689300537109375}},
                                               'http://localhost/dwm/drw.c': {'crawl_status': False,
                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                              'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/drw.h': {'crawl_status': False,
                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                              'stats': {'time': 0.0011920928955078125}},
                                               'http://localhost/dwm/dwm.1': {'crawl_status': False,
                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                              'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/dwm.c': {'crawl_status': False,
                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                              'stats': {'time': 0.0011920928955078125}},
                                               'http://localhost/dwm/dwm.png': {'crawl_status': False,
                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                'stats': {'time': 0.0011920928955078125}},
                                               'http://localhost/dwm/transient.c': {'crawl_status': False,
                                                                                    'reason': 'MAX_DEPTH_REACHED',
                                                                                    'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/util.c': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.001430511474609375}},
                                               'http://localhost/dwm/util.h': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.0011920928955078125}}},
                                     'response_status': 200,
                                     'stats': {'time': 3.328561782836914}},
           'http://localhost/eduAsk/': {'crawl_status': False,
                                        'reason': 'RESPONSE_FAIL',
                                        'response_error': 'Internal Server '
                                                          'Error',
                                        'response_status': 500,
                                        'stats': {'time': 3.6804676055908203}},
           'http://localhost/foundation/': {'crawl_status': False,
                                            'reason': 'RECURSIVE_LOOP',
                                            'stats': {'time': 4.568576812744141}},
           'http://localhost/guide-to-testing-in-django/': {'content': <Response [200]>,
                                                            'links': {'http://localhost/': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0026226043701171875}},
                                                                      'http://localhost/guide-to-testing-in-django/README.rst': {'crawl_status': False,
                                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                 'stats': {'time': 0.0021457672119140625}},
                                                                      'http://localhost/guide-to-testing-in-django/__init__.py': {'crawl_status': False,
                                                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                  'stats': {'time': 0.0021457672119140625}},
                                                                      'http://localhost/guide-to-testing-in-django/manage.py': {'crawl_status': False,
                                                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                'stats': {'time': 0.0019073486328125}},
                                                                      'http://localhost/guide-to-testing-in-django/polls.db': {'crawl_status': False,
                                                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                                                               'stats': {'time': 0.0021457672119140625}},
                                                                      'http://localhost/guide-to-testing-in-django/polls/': {'crawl_status': False,
                                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                                             'stats': {'time': 0.002384185791015625}},
                                                                      'http://localhost/guide-to-testing-in-django/settings.py': {'crawl_status': False,
                                                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                  'stats': {'time': 0.0021457672119140625}},
                                                                      'http://localhost/guide-to-testing-in-django/templates/': {'crawl_status': False,
                                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                 'stats': {'time': 0.0021457672119140625}},
                                                                      'http://localhost/guide-to-testing-in-django/urls.py': {'crawl_status': False,
                                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                                              'stats': {'time': 0.0019073486328125}}},
                                                            'response_status': 200,
                                                            'stats': {'time': 4.303216934204102}},
           'http://localhost/html/': {'content': <Response [200]>,
                                      'links': {'http://localhost/': {'crawl_status': False,
                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                      'stats': {'time': 0.00286102294921875}},
                                                'http://localhost/html/index.nginx-debian.html': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.002384185791015625}}},
                                      'response_status': 200,
                                      'stats': {'time': 3.7310123443603516}},
           'http://localhost/ipinfra-BitBucket/': {'content': <Response [200]>,
                                                   'links': {'http://localhost/': {'crawl_status': False,
                                                                                   'reason': 'MAX_DEPTH_REACHED',
                                                                                   'stats': {'time': 0.0030994415283203125}},
                                                             'http://localhost/ipinfra-BitBucket/ApacheVirtualHostConf.txt': {'crawl_status': False,
                                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                                              'stats': {'time': 0.0021457672119140625}},
                                                             'http://localhost/ipinfra-BitBucket/README.md': {'crawl_status': False,
                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                              'stats': {'time': 0.0021457672119140625}},
                                                             'http://localhost/ipinfra-BitBucket/allmodels/': {'crawl_status': False,
                                                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                                                               'stats': {'time': 0.0021457672119140625}},
                                                             'http://localhost/ipinfra-BitBucket/api_indiaproperty_dev.sublime-workspace': {'crawl_status': False,
                                                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                            'stats': {'time': 0.0019073486328125}},
                                                             'http://localhost/ipinfra-BitBucket/ipinfra/': {'crawl_status': False,
                                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                                             'stats': {'time': 0.0021457672119140625}},
                                                             'http://localhost/ipinfra-BitBucket/listings/': {'crawl_status': False,
                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                              'stats': {'time': 0.0019073486328125}},
                                                             'http://localhost/ipinfra-BitBucket/manage.py': {'crawl_status': False,
                                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                                              'stats': {'time': 0.0021457672119140625}}},
                                                   'response_status': 200,
                                                   'stats': {'time': 4.289865493774414}},
           'http://localhost/ipinfra/': {'content': <Response [200]>,
                                         'links': {'http://localhost/': {'crawl_status': False,
                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                         'stats': {'time': 0.0030994415283203125}},
                                                   'http://localhost/ipinfra/ApacheVirtualHostConf.txt': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.0016689300537109375}},
                                                   'http://localhost/ipinfra/README.md': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/assets/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/ipinfra/extras/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/ipinfra/gitFile.sh': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/ipinfra/': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/jsonRequest.json': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/log/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/logs/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/requirements/': {'crawl_status': False,
                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                              'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/schema.mwb': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/ipinfra/static/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0019073486328125}}},
                                         'response_status': 200,
                                         'stats': {'time': 4.389047622680664}},
           'http://localhost/phpinfo.php': {'content': <Response [200]>,
                                            'links': {'http://www.php.net/': {'crawl_status': False,
                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                              'stats': {'time': 0.002384185791015625}},
                                                      'http://www.zend.com/': {'crawl_status': False,
                                                                               'reason': 'MAX_DEPTH_REACHED',
                                                                               'stats': {'time': 0.001430511474609375}}},
                                            'response_status': 200,
                                            'stats': {'time': 10.863304138183594}},
           'http://localhost/phpmyadmin/': {'content': <Response [200]>,
                                            'links': {'http://localhost/phpmyadmin/doc/html/index.html': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.00476837158203125}},
                                                      'http://localhost/phpmyadmin/favicon.ico': {'crawl_status': False,
                                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                                  'stats': {'time': 0.0057220458984375}},
                                                      'http://localhost/phpmyadmin/phpmyadmin.css.php?server=1&amp;lang=en&amp;collation_connection=utf8_unicode_ci&amp;token=d576d2d4df76f897216abd1f17f51347&amp;nocache=2844124295ltr': {'crawl_status': False,
                                                                                                                                                                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                                                                                                                            'stats': {'time': 0.0057220458984375}},
                                                      'http://localhost/phpmyadmin/themes/pmahomme/jquery/jquery-ui-1.9.2.custom.css': {'crawl_status': False,
                                                                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                        'stats': {'time': 0.0050067901611328125}},
                                                      'http://localhost/phpmyadmin/url.php?url=http%3A%2F%2Fwww.phpmyadmin.net%2F': {'crawl_status': False,
                                                                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                                                                     'stats': {'time': 0.0050067901611328125}}},
                                            'response_status': 200,
                                            'stats': {'time': 21.12579345703125}},
           'http://localhost/startupguwahati/': {'content': <Response [200]>,
                                                 'links': {'http://localhost/': {'crawl_status': False,
                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                 'stats': {'time': 0.003337860107421875}},
                                                           'http://localhost/startupguwahati/README.md': {'crawl_status': False,
                                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                                          'stats': {'time': 0.0019073486328125}},
                                                           'http://localhost/startupguwahati/data/': {'crawl_status': False,
                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                      'stats': {'time': 0.0021457672119140625}},
                                                           'http://localhost/startupguwahati/libs/': {'crawl_status': False,
                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                      'stats': {'time': 0.0021457672119140625}},
                                                           'http://localhost/startupguwahati/openshiftlibs.py': {'crawl_status': False,
                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                 'stats': {'time': 0.0019073486328125}},
                                                           'http://localhost/startupguwahati/requirements.txt': {'crawl_status': False,
                                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                                 'stats': {'time': 0.0019073486328125}},
                                                           'http://localhost/startupguwahati/setup.py': {'crawl_status': False,
                                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                                         'stats': {'time': 0.0021457672119140625}},
                                                           'http://localhost/startupguwahati/wsgi/': {'crawl_status': False,
                                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                                      'stats': {'time': 0.0019073486328125}}},
                                                 'response_status': 200,
                                                 'stats': {'time': 4.276752471923828}},
           'http://localhost/tests/': {'content': <Response [200]>,
                                       'links': {'http://localhost/': {'crawl_status': False,
                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                       'stats': {'time': 0.0030994415283203125}},
                                                 'http://localhost/tests/tests.py': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0021457672119140625}}},
                                       'response_status': 200,
                                       'stats': {'time': 3.747701644897461}},
           'http://localhost/xyz/': {'content': <Response [200]>,
                                     'links': {'http://localhost/': {'crawl_status': False,
                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                     'stats': {'time': 0.00286102294921875}},
                                               'http://localhost/xyz/manage.py': {'crawl_status': False,
                                                                                  'reason': 'MAX_DEPTH_REACHED',
                                                                                  'stats': {'time': 0.0021457672119140625}},
                                               'http://localhost/xyz/tes/': {'crawl_status': False,
                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                             'stats': {'time': 0.0021457672119140625}},
                                               'http://localhost/xyz/xyz/': {'crawl_status': False,
                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                             'stats': {'time': 0.0021457672119140625}}},
                                     'response_status': 200,
                                     'stats': {'time': 3.74603271484375}},
           'http://localhost/zamboni/': {'content': <Response [200]>,
                                         'links': {'http://localhost/': {'crawl_status': False,
                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                         'stats': {'time': 0.00286102294921875}},
                                                   'http://localhost/zamboni/CONTRIBUTING.md': {'crawl_status': False,
                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/Dockerfile': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/LICENSE': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/Makefile': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/README.md': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/__init__.py': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/bin/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0026226043701171875}},
                                                   'http://localhost/zamboni/configs/': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/contribute.json': {'crawl_status': False,
                                                                                                'reason': 'MAX_DEPTH_REACHED',
                                                                                                'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/data/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/docs/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/fabfile.py': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/lib/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/locale/': {'crawl_status': False,
                                                                                        'reason': 'MAX_DEPTH_REACHED',
                                                                                        'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/logs/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/manage.py': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/media/': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/migrations/': {'crawl_status': False,
                                                                                            'reason': 'MAX_DEPTH_REACHED',
                                                                                            'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/mkt/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/package.json': {'crawl_status': False,
                                                                                             'reason': 'MAX_DEPTH_REACHED',
                                                                                             'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/requirements/': {'crawl_status': False,
                                                                                              'reason': 'MAX_DEPTH_REACHED',
                                                                                              'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/scripts/': {'crawl_status': False,
                                                                                         'reason': 'MAX_DEPTH_REACHED',
                                                                                         'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/services/': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/settings_test.py': {'crawl_status': False,
                                                                                                 'reason': 'MAX_DEPTH_REACHED',
                                                                                                 'stats': {'time': 0.0016689300537109375}},
                                                   'http://localhost/zamboni/setup.cfg': {'crawl_status': False,
                                                                                          'reason': 'MAX_DEPTH_REACHED',
                                                                                          'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/sites/': {'crawl_status': False,
                                                                                       'reason': 'MAX_DEPTH_REACHED',
                                                                                       'stats': {'time': 0.0021457672119140625}},
                                                   'http://localhost/zamboni/templates/': {'crawl_status': False,
                                                                                           'reason': 'MAX_DEPTH_REACHED',
                                                                                           'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/tmp/': {'crawl_status': False,
                                                                                     'reason': 'MAX_DEPTH_REACHED',
                                                                                     'stats': {'time': 0.0019073486328125}},
                                                   'http://localhost/zamboni/wsgi/': {'crawl_status': False,
                                                                                      'reason': 'MAX_DEPTH_REACHED',
                                                                                      'stats': {'time': 0.0021457672119140625}}},
                                         'response_status': 200,
                                         'stats': {'time': 5.265474319458008}}},
 'response_status': 200,
 'stats': {'time': 1146.6825008392334}}
